### PR TITLE
fix: skip ownership checks for ignored generated paths

### LINKED ISSUE #278: [Bug]: Exclude generated build directories from symbol ownership and trace coverage checks
### What area is affected?
CLI or runtime behavior

### What happened?
Trace validation currently assumes repository files under source and test roots are candidates for ownership checks, while the repository also tracks generated browser output under app/dist. Generated bundles and wasm loader files are not meaningful implementation symbols, so scanning them for ownership or symbol existence creates a class of false positives and future adoption friction for any repository with frontend build output.

The current spec also makes ownership strict: REQ-CORE-002 requires optional full symbol ownership checks, and SYU-trace-id-001 requires traced files to mention their owning specification ID. That combination is reasonable for authored source files, but not for dist-like directories.

### What did you expect to happen?
Ownership and symbol coverage should ignore standard generated directories such as dist, build, coverage, and target by default, while still letting repositories opt in if they genuinely want to validate generated artifacts.

### syu version
main

### Environment
Repository audit on Linux in the main syu workspace.

### Steps to reproduce
1. Inspect REQ-CORE-002 in docs/syu/requirements/core/validation.yaml.
2. Inspect the SYU-trace-id-001 rule description in docs/syu/features/validation/validation.yaml.
3. Observe that the repository also tracks app/dist build output.
4. Consider enabling or tightening symbol ownership in a workspace that tracks generated bundles.

### Logs, screenshots, or failing output
```shell
git ls-files app/dist
app/dist/assets/index-C1DQWMlk.css
app/dist/assets/index-DK0RrL4H.js
app/dist/assets/syu_app_wasm-BLC3TU7T.js
app/dist/assets/syu_app_wasm_bg-C58AZfzD.wasm
app/dist/favicon.svg
app/dist/index.html
```

### Before submitting
- [x] I searched for existing issues first.
- [x] I can share a minimal reproduction if more detail is needed.

### PR DESCRIPTION
**Pull request by tohboeh5**
## Linked issue or specification
- Closes #278

## Summary
- skip inline and sidecar ownership enforcement for paths already excluded from generated-path coverage
- keep the ignore list configurable so repositories can opt generated paths back in
- add regression tests for ignored and opt-in ownership behavior

## Validation
- scripts/ci/quality-gates.sh
- cargo run -- validate .
- scripts/ci/coverage.sh summary

### CODE REVIEW

File: src/command/check.rs [hunk 1]
```diff
@@ -2374,74 +2377,77 @@ fn verify_trace_reference(
...
-        OwnershipDeclaration::Satisfied => {}
-        OwnershipDeclaration::Missing { manifest_path } => {
-            let (message, suggestion) = match manifest_path {
-                Some(manifest_path) => {
-                    let manifest_display = manifest_path
-                        .strip_prefix(root)
-                        .unwrap_or(manifest_path.as_path());
-                    (
+    let ignored_paths = normalized_symbol_trace_coverage_ignored_paths(config);
+    if !path_matches_ignored_generated_directory(display_path, &ignored_paths) {
```
Comment (tohboeh5) [inline src/command/check.rs:2381]: This condition changes `validate.symbol_trace_coverage_ignored_paths` from a coverage-discovery filter into an ownership-enforcement bypass as well, but I couldnt find any matching config/help/docs update in this PR. That means users can now suppress `SYU-trace-id-001` for ignored paths without any user-facing explanation of that trade-off. Please document the new ownership interaction anywhere we explain this config knob, otherwise reviewers and adopters will keep reading it as "coverage only" and miss the weaker ownership guarantee.

**Comment by tohboeh5** [comment]
Overview review:

This is a worthwhile fix: the new helper and tests make the generated-path behavior much more consistent, and I confirmed the added ignored-path tests pass on the branch.

My main concern is the scope of the behavior change. `validate.symbol_trace_coverage_ignored_paths` now affects ownership enforcement as well as generated-path coverage, but the PR does not update any user-facing docs/help/config reference to explain that stronger opt-out. I left one inline comment on that point because the implementation is otherwise in good shape, but the changed contract is too implicit right now.
