### PR TITLE
test: cover every example syu.yaml freshness

### LINKED ISSUE #485: [Bug]: Cover every checked-in example syu.yaml with repository-quality freshness checks
### What area is affected?

Documentation or examples

### What happened?

The repository now ships multiple checked-in example workspaces, but repository-quality coverage still only guards some of the freshness contracts around example inputs. That leaves room for new example `syu.yaml` files to drift away from the current CLI version without the same protection.

### What did you expect to happen?

Every checked-in example workspace should get the same freshness protection for its versioned `syu.yaml` inputs so contributors do not accidentally ship stale example metadata.

### syu version

main

### Environment

Repository checkout, example workspaces, and `tests/repository_quality.rs`.

### Steps to reproduce

1. Inspect the checked-in examples under `examples/`.
2. Compare them with the repository-quality assertions that protect example freshness.
3. Notice that coverage is not expressed as a broad contract for every checked-in example `syu.yaml`.

### Logs, screenshots, or failing output

Relevant repository surfaces include `examples/**/syu.yaml` and the example freshness checks in `tests/repository_quality.rs`.

### Before submitting

- [x] I searched for existing issues first.
- [x] I can share a minimal reproduction if more detail is needed.

### PR DESCRIPTION
**Pull request by tohboeh5**
## Linked issue or specification
- Closes #485

## Summary
- replace per-example version assertions with a repository-wide scan of checked-in examples/**/syu.yaml files
- keep the existing example-specific content assertions alongside the broader freshness contract
- ensure future example workspaces automatically inherit current-version coverage

## Validation
- bash scripts/ci/pinned-npm.sh install app
- npm --prefix app ci
- cargo test --test repository_quality repository_ships_example_workspaces
- bash scripts/ci/quality-gates.sh
- cargo run -- validate .

### CODE REVIEW

File: tests/repository_quality.rs [hunk 1]
```diff
@@ -14,6 +18,26 @@ fn read_json(path: &str) -> Value {
     serde_json::from_str(&read_file(path)).expect("repository JSON should parse")
 }
 
+fn collect_named_files(root: &Path, file_name: &str, output: &mut Vec<PathBuf>) {
+    for entry in fs::read_dir(root).expect("directory should be readable") {
+        let entry = entry.expect("directory entry should exist");
+        let path = entry.path();
+
+        if path.is_dir() {
+            collect_named_files(&path, file_name, output);
```
Comment (tohboeh5) [inline tests/repository_quality.rs]: This broadens the contract from "top-level checked-in example workspaces" to "any `syu.yaml` anywhere under `examples/`". If we later add nested fixtures, support workspaces, or intentionally stale negative examples below an existing example root, this test will start failing even though those files are not first-class shipped examples. I think the scan should stay scoped to the example workspace roots the product actually documents.

**Comment by tohboeh5** [comment]
Overview review:

I like the direction here: replacing the per-example version assertions with a broader repository-quality contract is exactly the kind of maintenance guard this repository needs, and the test still keeps the example-specific content checks that explain why each workspace exists.

My main concern is scope. The new recursive walk currently treats every nested `examples/**/syu.yaml` file as a shipped example contract, which is stricter than the issue statement and could make future nested fixtures or support workspaces awkward to add. I left one inline comment on that point. If you tighten the scan to the documented example workspace roots, I think this will be a solid improvement.
