### PR TITLE
test: lock docs site helper contract

### LINKED ISSUE #486: [Bug]: Validate the docs-site install helper contract, not just the wrapper call site
### What area is affected?

Repository automation or CI

### What happened?

The docs-site install flow now routes through `scripts/ci/install-docs-site-deps.sh`, but the repository-quality contract is still easier to satisfy by only asserting that the wrapper mentions the helper. That leaves the actual clean-install behavior less protected than the call site.

### What did you expect to happen?

Repository-quality coverage should lock in the helper script's real contract: clean reinstall behavior, the expected `npm --prefix website ci` step, and the maintainer-facing reason this helper exists.

### syu version

main

### Environment

Repository checkout, `scripts/ci/validate-website.sh`, `scripts/ci/install-docs-site-deps.sh`, and `tests/repository_quality.rs`.

### Steps to reproduce

1. Inspect `scripts/ci/validate-website.sh`.
2. Inspect `scripts/ci/install-docs-site-deps.sh`.
3. Compare both with the current repository-quality assertions.
4. Notice that the helper behavior itself is not protected as strongly as the wrapper reference.

### Logs, screenshots, or failing output

Relevant files: `scripts/ci/validate-website.sh`, `scripts/ci/install-docs-site-deps.sh`, `tests/repository_quality.rs`.

### Before submitting

- [x] I searched for existing issues first.
- [x] I can share a minimal reproduction if more detail is needed.

### PR DESCRIPTION
**Pull request by tohboeh5**
## Summary
- strengthen repository-quality assertions around scripts/ci/install-docs-site-deps.sh itself
- lock in the helper's clean reinstall loop, repo-root setup, and website npm ci contract

## Testing
- bash scripts/ci/pinned-npm.sh install app
- npm --prefix app ci
- bash scripts/ci/quality-gates.sh
- cargo run -- validate .

Closes #486

### CODE REVIEW

File: tests/repository_quality.rs [hunk 1]
```diff
@@ -50,9 +50,16 @@ fn repository_declares_precommit_and_quality_gates() {
     assert!(validate_website_script.contains("scripts/ci/quality-gates.sh"));
     assert!(validate_website_script.contains("install-docs-site-deps.sh"));
     assert!(validate_website_script.contains("npm --prefix website run build"));
+    assert!(install_docs_site_deps_script.contains("set -euo pipefail"));
+    assert!(install_docs_site_deps_script.contains("repo_root="));
+    assert!(install_docs_site_deps_script.contains("cd \"$repo_root\""));
     assert!(install_docs_site_deps_script.contains("Branch switches can leave behind"));
     assert!(install_docs_site_deps_script.contains("website/node_modules"));
+    assert!(install_docs_site_deps_script.contains("for attempt in range(5):"));
```
Comment (tohboeh5) [inline tests/repository_quality.rs]: This assertion block is locking the current implementation shape of `install-docs-site-deps.sh`, not its externally visible contract. Renaming `repo_root`, changing the retry loop from Python to shell, or extracting the backoff constant would all fail repository-wide CI even if the helper still cleaned stale `website/node_modules` and ran `npm --prefix website ci` correctly. Could we keep the test focused on the observable guarantees we actually want to preserve?

**Comment by tohboeh5** [comment]
Overview review:\n\nI like the intent here: the repository-quality suite should protect the docs-site helper because that script is part of the contributor workflow contract.\n\nMy concern is that the new assertions pin several internal implementation details instead of the contract itself. I left one inline comment on that block because it would make harmless refactors fail CI without changing the observable helper behavior.
