### PR TITLE
fix: make docs-site validation installs repeatable

### LINKED ISSUE #439: [Bug]: Make repeated docs-site installs idempotent in reused worktrees
### What area is affected?

Repository automation or CI

### What happened?

Repeated docs-site validation in a reused checkout can fail before the build even starts because `npm --prefix website ci` trips over an existing `website/node_modules` tree with `ENOTEMPTY`. I hit this multiple times while validating docs-only branches back to back in the same repository checkout.

That makes the documented validation flow feel non-idempotent: running the same command twice in a healthy worktree can require manual cleanup that the docs never mention.

### What did you expect to happen?

The documented docs-site validation path should be safe to re-run in the same checkout without manual `node_modules` cleanup, or the repository should provide a cleanup-aware wrapper that makes the happy path deterministic.

### syu version

main

### Environment

Linux, repository checkout with repeated `npm --prefix website ci` / `npm --prefix website run build` runs across multiple branches and worktrees.

### Steps to reproduce

1. Start from a checkout where `website/node_modules` already exists from a prior docs-site build.
2. Run `npm --prefix website ci` again after switching branches or re-running validation.
3. Observe intermittent `ENOTEMPTY` failures while npm removes existing package directories.

### Logs, screenshots, or failing output

```shell
npm error code ENOTEMPTY
npm error syscall rmdir
npm error path /workspaces/.../website/node_modules/@docusaurus
npm error ENOTEMPTY: directory not empty, rmdir '.../website/node_modules/@docusaurus'
```

### Before submitting

- [x] I searched for existing issues first.
- [x] I can share a minimal reproduction if more detail is needed.

### PR DESCRIPTION
**Pull request by tohboeh5**
## Summary
- route validate-website.sh through the cleanup-aware docs-site dependency installer
- keep the repository quality assertion aligned with the new validation path
- validate the docs-site wrapper twice in the same worktree to confirm repeated runs stay deterministic

Closes #439

### CODE REVIEW

File: tests/repository_quality.rs [hunk 1]
```diff
@@ -47,7 +47,7 @@ fn repository_declares_precommit_and_quality_gates() {
     assert!(validate_website_script.contains("FEAT-QUALITY-001"));
     assert!(validate_website_script.contains("validate_website"));
     assert!(validate_website_script.contains("scripts/ci/quality-gates.sh"));
-    assert!(validate_website_script.contains("npm --prefix website ci"));
+    assert!(validate_website_script.contains("install-docs-site-deps.sh"));
```
Comment (tohboeh5) [inline tests/repository_quality.rs:51]: Now that the docs-site install behavior moved into `scripts/ci/install-docs-site-deps.sh`, this assertion only proves the wrapper script mentions the helper name. It no longer guards the actual contract that mattered here (`website/node_modules` gets rebuilt from a clean slate and `npm --prefix website ci` still runs). Please add repository-quality coverage for the helper script contents too, otherwise a future regression inside that helper can slip through while this test still passes.

**Comment by tohboeh5** [comment]
Overview review:

The functional fix looks right: switching `validate-website` to the shared install helper matches the repo guidance better, and the website validation flow completed successfully in local execution.

The main thing still missing is protection against future regressions. The updated repository-quality test now checks only that the wrapper calls `install-docs-site-deps.sh`, not that the helper still performs the clean reinstall behavior this PR is relying on. I left one inline comment on that gap.

With that extra coverage in place, this would be a tidy and focused fix for the repeated-install problem.
