### PR TITLE
docs: fix stale README anchors in getting-started

### LINKED ISSUE #395: [Bug]: Fix stale README anchor links in the getting-started guide
## What area is affected?
Documentation or generated docs

## What happened?
`docs/guide/getting-started.md` still links back to README anchors that no longer exist after the README chooser/fit-check reshuffle. The guide currently points to `#quick-start` and `#before-you-install-check-whether-syu-fits-this-repository`, but the current README headings are `#choose-your-path` and `#is-syu-right-for-this-repository`.

That means the “jump back to the README” guidance sends first-time readers to broken anchors right at the moment they are trying to choose an onboarding path.

## What did you expect to happen?
The getting-started guide should link to stable README anchors that exist in the checked-in README, or it should stop hardcoding GitHub heading anchors when those anchors are likely to drift.

## syu version
main

## Environment
Observed in the checked-in documentation on Linux while reviewing the current `main` branch.

## Steps to reproduce
1. Open `docs/guide/getting-started.md`.
2. Follow the links to the README quick start and repository-fit sections.
3. Compare them with the headings that actually exist in `README.md`.

## Logs, screenshots, or failing output
- `docs/guide/getting-started.md#L13` links to `README.md#quick-start`
- `docs/guide/getting-started.md#L30` links to `README.md#before-you-install-check-whether-syu-fits-this-repository`
- `README.md` currently uses `## Choose your path` and `## Is syu right for this repository?`

### PR DESCRIPTION
**Pull request by tohboeh5**
## Summary
- point the getting-started README backlinks at anchors that still exist
- update repository-quality expectations to match the current README chooser anchor

## Linked issue or specification
- Closes #395

### CODE REVIEW

File: tests/repository_quality.rs [hunk 1]
```diff
@@ -368,7 +368,8 @@ fn repository_declares_documentation_guides() {
         getting_started.contains("[trace adapter capability matrix](./trace-adapter-support.md)")
     );
     assert!(
-        getting_started.contains("https://github.com/ugoite/syu/blob/main/README.md#quick-start")
+        getting_started
```
Comment (tohboeh5) [inline tests/repository_quality.rs:371]: This updates the assertion for the `#choose-your-path` backlink, but the second anchor change in `getting-started.md` (`#is-syu-right-for-this-repository`) still has no repository-quality coverage. Without a guard for that link too, we can regress back into stale README anchors the next time the chooser headings move.

**Comment by tohboeh5** [comment]
## Overview

The link fixes themselves look right, and tightening the repository-quality check is exactly the right follow-up. I left one blocking inline note because the new test only covers one of the two updated README anchors, so this PR still leaves a silent drift path open for the repository-fit backlink.
