### PR TITLE
fix(FEAT-CHECK-001): guard escaped coverage paths

### LINKED ISSUE #563: [Bug]: Coverage discovery should not panic on scanned files that escape the workspace root
### What area is affected?

CLI or runtime behavior

### What happened?

Coverage discovery still has multiple `strip_prefix(root).expect("scanned file should remain under the workspace root")` calls in `src/coverage.rs`.

That is safe only if every scanned path always stays under the workspace root. If a repository contains symlinked source/test entries or a future scanner starts yielding canonicalized paths from outside the root, `syu validate --require-symbol-trace-coverage` can panic instead of surfacing a regular validation issue.

### What did you expect to happen?

Coverage discovery should treat out-of-root scanned files as a normal validation/runtime error and continue reporting cleanly, not panic with an `expect(...)` failure.

### syu version

main

### Environment

Linux, workspaces that include symlinked source trees or unusual scanner path handling

### Steps to reproduce

1. Create a workspace with `validate.require_symbol_trace_coverage: true`.
2. Introduce a scanned source/test path that resolves outside the workspace root (for example through a symlinked tree).
3. Run `syu validate .`.
4. Observe that the code path in `src/coverage.rs` uses `expect(...)` rather than a recoverable error.

### Logs, screenshots, or failing output

Representative locations in `src/coverage.rs` include lines with:

```rust
.strip_prefix(root)
.expect("scanned file should remain under the workspace root")
```

This pattern currently appears in multiple language discovery passes.

### Before submitting

- [x] I searched for existing issues first.
- [x] I can share a minimal reproduction if more detail is needed.

### PR DESCRIPTION
**Pull request by tohboeh5**
## Summary
- replace coverage discovery path panics with recoverable inventory issues
- keep each language scanner moving when one scanned file escapes the workspace root
- cover both the escaped-path guard and the continued scan behavior with focused coverage tests

## Linked issue or specification
- Closing keyword issue: Closes #563
- Requirement / feature IDs: FEAT-CHECK-001

## Validation
- [x] `scripts/ci/quality-gates.sh`
- [x] `scripts/ci/coverage.sh summary` (required when Rust logic changes)
- [x] `cargo run -- validate .`
- [x] Docs, examples, or self-spec updated when behavior changed

## Release notes
- [ ] This change should appear in the next release notes
- [x] No release note needed

### CODE REVIEW

File: src/coverage.rs [hunk 1]
```diff
@@ -1352,6 +1328,24 @@ fn should_skip_generated_directory(
         .is_some_and(|relative| path_matches_ignored_generated_directory(relative, ignored_paths))
```
Comment (tohboeh5) [inline src/coverage.rs:1408]: This is better than panicking, but the callers still use `?`, so the first escaped path now aborts the entire coverage discovery pass for that language. That means one bad path can suppress unrelated coverage findings from the rest of the workspace. Can we surface the issue and keep scanning the remaining files instead of turning it into an early-return for the whole pass?

**Comment by tohboeh5** [comment]
Overview:

Centralizing the workspace-root guard is the right fix, and replacing the `expect(...)` panics with a real `Issue` is a clear reliability improvement. My remaining concern is recovery scope. The new helper still bubbles an error out of each language discovery pass immediately, so one escaped file can stop coverage inventory for the rest of that language instead of reporting the bad path and continuing. I would prefer to keep the new issue reporting while making the scanner as non-fatal as possible for unrelated files.
