### PR TITLE
test: cover every checked-in example config

### LINKED ISSUE #485: [Bug]: Cover every checked-in example syu.yaml with repository-quality freshness checks
### What area is affected?

Documentation or examples

### What happened?

The repository now ships multiple checked-in example workspaces, but repository-quality coverage still only guards some of the freshness contracts around example inputs. That leaves room for new example `syu.yaml` files to drift away from the current CLI version without the same protection.

### What did you expect to happen?

Every checked-in example workspace should get the same freshness protection for its versioned `syu.yaml` inputs so contributors do not accidentally ship stale example metadata.

### syu version

main

### Environment

Repository checkout, example workspaces, and `tests/repository_quality.rs`.

### Steps to reproduce

1. Inspect the checked-in examples under `examples/`.
2. Compare them with the repository-quality assertions that protect example freshness.
3. Notice that coverage is not expressed as a broad contract for every checked-in example `syu.yaml`.

### Logs, screenshots, or failing output

Relevant repository surfaces include `examples/**/syu.yaml` and the example freshness checks in `tests/repository_quality.rs`.

### Before submitting

- [x] I searched for existing issues first.
- [x] I can share a minimal reproduction if more detail is needed.

### PR DESCRIPTION
**Pull request by tohboeh5**
## Summary
- enumerate top-level checked-in examples instead of hard-coding version checks one by one
- require every example `syu.yaml` to carry the current CLI version
- require every example workspace to have a dedicated validation smoke test

Closes #485

### CODE REVIEW

File: tests/repository_quality.rs [hunk 1]
```diff
@@ -720,55 +742,60 @@ fn repository_declares_devcontainer_configuration() {
...
+            "go-only",
+            "polyglot",
+            "python-only",
+            "rust-only",
+            "team-scale",
+        ]
+    );
+    for example_name in &example_workspace_names {
+        let config = read_file(&format!("examples/{example_name}/syu.yaml"));
+        let validate_test_name = format!("{}_example_validates", example_name.replace('-', "_"));
```
Comment (tohboeh5) [inline tests/repository_quality.rs]: This assertion couples the repository-quality contract to the current Rust test function naming convention rather than the user-facing guarantee from the issue. A future refactor to a shared helper, table-driven test, or renamed smoke test would fail here even if every checked-in example still validates. I think the contract should point at the actual example-validation coverage path, not a string match on `*_example_validates` names.

**Comment by tohboeh5** [comment]
Overview review:\n\nI like the direction here: replacing the repeated per-example assertions with a single inventory-style check is cleaner, and it moves the repository-quality contract closer to the actual user concern of every checked-in example staying current and covered.\n\nMy concern is that the new test still reaches for a fairly implementation-shaped signal when it checks for `*_example_validates` names in the test source text. That makes the contract brittle against harmless test refactors even if example coverage still exists. I left one inline comment on that point.
