### PR TITLE
fix: warn before advertising non-loopback app url

### LINKED ISSUE #309: [Bug]: Print the non-loopback security warning before syu app advertises the listening URL
### What area is affected?
CLI or runtime behavior

### What happened?
When syu app binds to a non-loopback address, it prints the listening URL before it prints the warning that workspace data may be reachable from other machines on the network.

That ordering is risky for first-time users because the command advertises the URL before it explains the security implication of exposing the local workspace over the network.

### What did you expect to happen?
The non-loopback warning should be shown before syu app prints the listening URL or browser-open guidance so users see the exposure warning first.

### syu version
main

### Environment
Local CLI usage of syu app with a non-loopback bind such as --bind 0.0.0.0.

### Steps to reproduce
1. Run syu app --bind 0.0.0.0 .
2. Observe the startup output order.
3. Notice that the listening URL is printed before the warning about network exposure.

### Logs, screenshots, or failing output
src/command/app.rs prints "syu app listening on ..." before it later emits the non_loopback_warning_lines startup messages.

### Before submitting
- [x] I searched for existing issues first.
- [x] I can share a minimal reproduction if more detail is needed.

### PR DESCRIPTION
**Pull request by tohboeh5**
## Summary
- print the non-loopback exposure warning before the app advertises its listening URL
- flush startup lines as they are emitted so the warning is visible before later guidance
- cover the new startup ordering in app command tests

Closes #309

### CODE REVIEW

File: src/command/app.rs [hunk 1]
```diff
@@ -222,6 +210,9 @@ pub fn run_app_command(args: &AppArgs) -> Result<i32> {
 fn startup_lines(local_addr: SocketAddr) -> Vec<StartupLine> {
```
Comment (tohboeh5) [inline src/command/app.rs]: This is still relying on stderr for the warning and stdout for the URL, so the relative order is only best-effort. A human running the command interactively will usually see the warning first, but merged logs and redirected output can still show the listening URL before the warning. If the guarantee matters, emit the whole startup sequence on one stream.

**Comment by tohboeh5** [comment]
The change moves in the right direction by trying to keep the warning ahead of the public bind announcement. My main concern is the same ordering contract as in the earlier app-startup work: splitting the startup sequence across stdout and stderr makes the guarantee weaker than the user-facing wording suggests.

File: src/command/app.rs [hunk 2]
```diff
@@ -194,22 +194,10 @@ pub fn run_app_command(args: &AppArgs) -> Result<i32> {
                 .await
                 .context("local app server exited unexpectedly")
         });
-        println!("syu app listening on http://{local_addr}");
         tokio::task::spawn_blocking(move || wait_for_ready(local_addr))
```
Comment (tohboeh5) [inline src/command/app.rs:192]: This still waits for `wait_for_ready(local_addr)` to finish before printing the non-loopback warning. That means the security warning is silent during startup delays or readiness hangs, even though the process has already bound to a public interface. If the intent is to warn users as soon as we know the bind is public, can we emit the warning lines before the readiness probe and only keep the `listening`/`ready` messages behind the probe?

**Comment by tohboeh5** [comment]
Overall impression: this heads in the right direction because it keeps the warning ahead of the advertised URL output and adds coverage for the stdout/stderr split. The remaining concern is that the warning is still delayed until after the readiness probe completes, so a slow or stuck startup can leave users with no early signal that they chose a public bind. I left one inline comment on that startup ordering edge case.

**Comment by tohboeh5** [comment]
Overview

This is a sensible security/UX fix. Moving the non-loopback warning ahead of the advertised URL makes the risk harder to miss, and the extracted startup-line helper keeps the behavior easy to test. I did not find a substantive diff-local issue in the current patch.
